Devices:
  -
    deviceId: 192.168.31.67
    port: 5555
    deviceName: pptv
    serverPort: 4723
    bootstrApport: 4823
    platformName: Android
    platformVersion: 5.0.1
    server: 127.0.0.1
    packageName: com.pptv.tvsports
    appActivity: .activity.HomeActivity
